create static user to just get the email address once
arup-group/GSA-Grasshopper pull request #143
Opened 2022-07-31 21:27 UTC by kpne

2022-08-01 07:06 UTC, tlmnrnhrdt commented
@kpne what´s this good for? is getting the email adress time consuming?

2022-08-03 08:15 UTC, tlmnrnhrdt requested changes
Finally some requested changes ;)

2022-08-03 08:15 UTC, tlmnrnhrdt commented on GhSA/Helpers/PostHog.cs
> +    public class User
if it´s public it deserves its own file.. ;) 
I guess it can be private though?

2022-08-03 08:15 UTC, tlmnrnhrdt commented on GhSA/Helpers/PostHog.cs
> +    private static User thisUser = null;
fields in capital! :]

2022-08-03 08:15 UTC, tlmnrnhrdt commented on GhSA/Helpers/PostHog.cs
> +    private static User thisUser = null;
other than there is a good reason for lower case..

2022-08-03 08:15 UTC, tlmnrnhrdt commented on GhSA/Helpers/PostHog.cs
> +            var task = Task.Run(() => UserPrincipal.Current.EmailAddress);
this looks like it should go to a method outside the get/set

2022-08-03 08:15 UTC, tlmnrnhrdt commented on GhSA/Helpers/PostHog.cs
> +  public static class PostHogUser
that static class is unnecessary?!

2022-08-03 08:15 UTC, tlmnrnhrdt commented on GhSA/Helpers/PostHog.cs
> +          thisUser = new User();
this.thisUser?

I think what you are trying to do is called a 'singleton': https://www.google.com/search?q=singleton

2022-08-04 07:46 UTC, kpne commented
> @kpne what´s this good for? is getting the email adress time consuming?

Yes, it can be if user is not on a domain UserPrincipal.Current.EmailAddress will timeout.

2022-08-04 08:35 UTC, tlmnrnhrdt approved these changes

2022-08-04 08:40 UTC, merged