gsagh-239 reaction force diagrams
arup-group/GSA-Grasshopper pull request #332
Opened 2023-02-27 14:32 UTC by DominikaLos

2023-02-27 14:49 UTC, tlmnrnhrdt commented on GsaGH/Components/5_Results/ReactionForceDiagrams.cs
> +namespace GsaGH.Components._5_Results
Can we move this to namespace `GsaGH.Components` please?

2023-02-27 14:49 UTC, tlmnrnhrdt commented on GsaGH/Components/5_Results/ReactionForceDiagrams.cs
> +    protected override void RegisterInputParams(GH_InputParamManager pManager)
Sorry, I meant putting those after the constructor (before all the other methods..)

2023-02-27 14:49 UTC, tlmnrnhrdt commented on GsaGH/Components/5_Results/ReactionForceDiagrams.cs
> +    public ReactionForceDiagrams() : base("Reaction Force Diagrams",
that´s technically a constructor and not a method no?

2023-02-27 14:49 UTC, tlmnrnhrdt commented on GsaGH/Components/5_Results/ReactionForceDiagrams.cs
> +      _reactionForceVectors.ForEach(force =>
should we use `this` everywhere?

2023-02-28 08:50 UTC, tlmnrnhrdt requested changes

2023-02-28 08:50 UTC, tlmnrnhrdt commented on GsaGH/Components/5_Results/ReactionForceDiagrams.cs
> +  /// Component to display GSA node result contours
this should say something about reaction forces no?

2023-03-03 12:22 UTC, kpne approved these changes

2023-03-03 13:45 UTC, merged