GsaGH-307 update import methods
arup-group/GSA-Grasshopper pull request #421
Opened 2023-06-15 18:45 UTC by kpne

2023-06-16 09:05 UTC, DominikaLos submitted a review, later dismissed

2023-06-16 09:05 UTC, DominikaLos commented on GsaGH/Components/1_Properties/EditMaterial.cs
> +      //if (da.GetData(3, ref ghTyp)) {
as above

2023-06-16 09:05 UTC, DominikaLos commented on GsaGH/Components/GraveyardComp/CreateCustomMaterial_OBSOLETE.cs
> +      //switch (_mode) {
as above

2023-06-16 09:05 UTC, DominikaLos commented on GsaGH/Components/GraveyardComp/CreateMaterial2_OBSOLETE.cs
> +      //switch (_selectedItems[0]) {
as above

2023-06-16 09:05 UTC, DominikaLos commented on GsaGH/Components/GraveyardComp/CreateMaterial_OBSOLETE.cs
> +      //switch (_mode) {
as above

2023-06-16 09:05 UTC, DominikaLos commented on GsaGH/Components/GraveyardComp/EditMaterial_OBSOLETE.cs
> +        //if (da.GetData(2, ref ghTyp)) {
as above

2023-06-16 09:05 UTC, DominikaLos commented on GsaGHTests/1_BaseParameters/1_Properties/GsaProp2dTest.cs
> +      //var mat = new GsaMaterial((int)materialType) {
as above

2023-06-16 09:05 UTC, DominikaLos commented on GsaGHTests/1_BaseParameters/1_Properties/GsaSectionTest.cs
> +        //Material = {
as above

2023-06-20 11:33 UTC, kpne commented on GsaGH/Components/1_Properties/CreateCustomMaterial.cs
> +      material.Id = 0;
done

2023-06-20 11:42 UTC, kpne commented on GsaGH/Components/1_Properties/EditMaterial.cs
> +      //if (da.GetData(3, ref ghTyp)) {
done

2023-06-20 11:42 UTC, kpne commented on GsaGH/Components/GraveyardComp/CreateCustomMaterial_OBSOLETE.cs
> +      //switch (_mode) {
uncommented

2023-06-20 11:43 UTC, kpne commented on GsaGH/Components/GraveyardComp/CreateMaterial_OBSOLETE.cs
> +      //switch (_mode) {
uncommented

2023-06-20 11:43 UTC, kpne commented on GsaGH/Components/GraveyardComp/EditMaterial_OBSOLETE.cs
> +        //if (da.GetData(2, ref ghTyp)) {
uncommented

2023-06-20 12:42 UTC, kpne commented on GsaGH/Components/GraveyardComp/CreateMaterial2_OBSOLETE.cs
> +      //switch (_selectedItems[0]) {
updated with error message

2023-06-21 18:56 UTC, kpne commented on GsaGHTests/1_BaseParameters/1_Properties/GsaSectionTest.cs
> +        //Material = {
updated test

2023-06-21 18:56 UTC, kpne commented on GsaGHTests/1_BaseParameters/1_Properties/GsaProp2dTest.cs
> +      //var mat = new GsaMaterial((int)materialType) {
updated test

2023-06-22 10:16 UTC, kpne commented on GsaGH/Components/GraveyardComp/EditMaterial_OBSOLETE.cs
> +        //if (da.GetData(2, ref ghTyp)) {
updated

2023-06-22 11:54 UTC, DominikaLos requested changes

2023-06-22 13:47 UTC, kpne commented on GsaGH/Components/GraveyardComp/EditMaterial_OBSOLETE.cs
> +        material = materialGoo.Value.Duplicate(true);
https://github.com/arup-group/GSA-Grasshopper/pull/421/commits/6561e960b29bc4ac300fb1f8ac61713bd8d07cef

2023-06-22 13:48 UTC, kpne commented on GsaGH/Components/GraveyardComp/CreateMaterial_OBSOLETE.cs
> +      AddRuntimeMessage(GH_RuntimeMessageLevel.Error,
https://github.com/arup-group/GSA-Grasshopper/pull/421/commits/6594556cb4fc749ed8ec18d319f016e16fd8e5ce

2023-06-26 08:53 UTC, DominikaLos approved these changes

2023-06-26 14:19 UTC, merged