GSAGH-473 Update groups default value from 0 to 1 for members/elements created using GsaGH.
arup-group/GSA-Grasshopper pull request #716
Opened 2024-10-22 09:43 UTC by DominikaLos

2024-10-23 11:05 UTC, SandeepArup reviewed
@DominikaLos @psarras We agreed to look for element also but still getting zero for element. I have attached .gh file in ticket to have a look

2024-10-24 04:16 UTC, SandeepArup commented on GsaGH/Parameters/2_Geometry/GsaModelDefaultValues.cs
> +  public struct GsaMemberDefaults {
@DominikaLos @psarras I feel this is not required. Just look for wrapper class "public class GSAElement" and do all default initilization there else you will endup making changes at multiple places and even for load panel

2024-10-24 08:52 UTC, psarras commented on GsaGH/Helpers/GsaAPI/GsaElement.cs
> +      LoadPanelElelment.Group = element.Group == 0 ? 1 : element.Group;
typo: LoadPanelElelment

2024-10-24 08:52 UTC, psarras commented on GsaGH/Parameters/2_Geometry/GsaElement1d.cs
>        }
is this a method? It repeats further down

2024-10-24 08:52 UTC, psarras commented on GsaGH/Parameters/2_Geometry/GsaMember3d.cs
>        };
is this repeated? Wrap it in a method

2024-10-24 08:52 UTC, psarras commented on GsaGH/Parameters/2_Geometry/GsaMember3d.cs
>        };
with this

2024-10-24 08:52 UTC, psarras commented on GsaGH/Parameters/2_Geometry/GsaMember2d.cs
>        };
wrap it

2024-10-24 08:52 UTC, psarras commented on GsaGH/Parameters/2_Geometry/GsaMember2d.cs
>        };
wrap it

2024-10-24 08:52 UTC, psarras commented on GsaGHTests/3_Components/2_Geometry/CreateElement2dTests.cs
```csharp
[Fact]
public void GroupsShouldDefaultToOne()
{
    var element = new Element();
    var gsaElement = GSAElement(element);
    Assert.Equal(1, gsaElement.group);
}
[Fact]
public void NonDefaultGroupsShouldNotBeModified()
{
    var element = new Element();
    element.group = 2;
    var gsaElement = GSAElement(element);
    Assert.Equal(2, gsaElement.group);
}


```

2024-10-30 12:07 UTC, psarras requested changes

2024-10-31 15:02 UTC, psarras reviewed
checked members refactoring, looks good

2024-11-18 13:49 UTC, psarras approved these changes

2024-11-18 13:49 UTC, merged