task: updated Gsa opening process
arup-group/GSA-Grasshopper pull request #728
Opened 2024-11-25 10:18 UTC by DominikaLos

2024-11-25 11:55 UTC, psarras requested changes

2024-11-25 11:55 UTC, psarras commented on GsaGH/Components/0_Model/SaveGsaModel.cs
> +      Process.Start(programFiles + @"\Oasys\GSA 10.2\GSA.exe", fullPath);
Use Path.Combine?

2024-11-25 12:41 UTC, DominikaLos commented on GsaGH/Components/0_Model/SaveGsaModel.cs
> +      Process.Start(programFiles + @"\Oasys\GSA 10.2\GSA.exe", fullPath);
will do

2024-11-26 17:33 UTC, psarras approved these changes

2024-11-27 09:49 UTC, SandeepArup approved these changes

2024-11-27 09:49 UTC, merged